### ISSUE TITLE
Would like to try it but install fails

### ISSUE THREAD

**Issue by ghost** [Roguelazer/muttdown#1]
% pip install --upgrade Markdown PyYAML pynliner                                                                                              12:06
Requirement already up-to-date: Markdown in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: PyYAML in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: pynliner in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: BeautifulSoup<4.0,>=3.2.1 in /usr/local/lib/python2.7/site-packages (from pynliner)
Requirement already up-to-date: cssutils>=0.9.7 in /usr/local/lib/python2.7/site-packages (from pynliner)
% pip install muttdown                                                                                                                        12:07
Collecting muttdown
  Using cached muttdown-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/g1/mvjqb71n3b1cwv6vb7_wv7hm0000z8/T/pip-build-nOX96W/muttdown/setup.py", line 29, in <module>
        install_requires, dependency_links = get_install_requirements()
      File "/private/var/folders/g1/mvjqb71n3b1cwv6vb7_wv7hm0000z8/T/pip-build-nOX96W/muttdown/setup.py", line 20, in get_install_requirements
        for ir in parse_requirements('requirements.txt', options=opts):
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_file.py", line 70, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/g1/mvjqb71n3b1cwv6vb7_wv7hm0000z8/T/pip-build-nOX96W/muttdown

**Comment by Roguelazer** [comment]
This should work since 3d673e56963142e18e9ca9cb78dc536627c63a6f

Give it another try and let me know.
