### ISSUE TITLE
Error when trying to run gpg command as smtp_password_command

### ISSUE THREAD

**Issue by jacklenox** [Roguelazer/muttdown#13]
Hello, I've just switched machines and have been setting things up as I usually have them. I seem to be having an issue with the `smtp_password_command` parameter. My yaml file looks like this:

```yaml
smtp_host: smtp.gmail.com
smtp_port: 465
smtp_ssl: true
smtp_username: jack.lenox@gmail.com
smtp_password_command: gpg -d --no-tty /home/jacklenox/.passwd/gmail.gpg
```

But when I try to send an email, I get the following error.

```
Traceback (most recent call last):
  File "/home/jacklenox/.local/bin/muttdown", line 11, in <module>
    sys.exit(main())
  File "/home/jacklenox/.local/lib/python3.6/site-packages/muttdown/main.py",
line 169, in main
    conn = smtp_connection(c)
  File "/home/jacklenox/.local/lib/python3.6/site-packages/muttdown/main.py",
line 120, in smtp_connection
    conn.login(c.smtp_username, c.smtp_password)
  File "/home/jacklenox/.local/lib/python3.6/site-packages/muttdown/config.py",
line 104, in smtp_password
    return check_output(self._config['smtp_password_command'],
shell=True).rstrip('\n')
TypeError: a bytes-like object is required, not 'str'
```

If I replace `smtp_password_command` with the decrypted `smtp_password`, everything works fine. And if I try to run the GPG command on its own, equally everything works.

Any thoughts?

**Comment by Roguelazer** [comment]
Ah, this is almost certainly a Python 3.6 incompatibility. I will fix it.

**Comment by jacklenox** [comment]
Thanks @Roguelazer!

**Comment by Roguelazer** [comment]
Version 0.3.2 has just been released in Github and PyPI which should fix this issue.
