### ISSUE TITLE
String vs Bytes Error

### ISSUE THREAD

**Issue by guyest** [Roguelazer/muttdown#15]
On python 3.7 running on arch linux, a simple string piped to muttdown via echo on commandline does not parse properly, raising an error that a bytes object is expected, not string. The email still sends but is blank, unfortunately. The offending line seems to be `main.py(166)`:

` proc.communicate(rebuilt.as_string())`

And I got it work by changing that line to:

` proc.communicate(rebuilt.as_string().encode())`

**Comment by Roguelazer** [comment]
This is fixed in version 0.3.3, which is now on PyPI.
