### ISSUE TITLE
py2 +muttdown 0.3.3  unicodeDecodeError with -s 

### ISSUE THREAD

**Issue by monkeyxite** [Roguelazer/muttdown#18]
There was py2 unicode error popping when -s pass thu own msmtp:

 "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 848: ordinal not in range(128)"

**Comment by Roguelazer** [comment]
#20 ought to fix this

**Comment by Roguelazer** [comment]
This is fixed in the forthcoming 0.3.4
