### ISSUE TITLE
UnicodeEncodeError for non-ASCII characters in body

### ISSUE THREAD

**Issue by rlue** [Roguelazer/muttdown#25]
Sending an email with a smartquote (U+2019) in the subject works fine:

```
$ muttdown -c /home/rlue/.config/muttdown.yml -f "ryan.lue@example.com" -- "ryan.lue@example.com"
Subject: What’s the big idea

Lorem ipsum dolor
```

But if that smartquote appears in the body, then sending the email fails:

```
$ muttdown -c /home/rlue/.config/muttdown.yml -f "ryan.lue@example.com" -- "ryan.lue@example.com"
Subject: Lorem ipsum dolor

What’s the big idea?
Traceback (most recent call last):
  File "/usr/local/bin/muttdown", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/muttdown/main.py", line 189, in main
    conn.sendmail(args.envelope_from, args.addresses, rebuilt.as_string())
  File "/usr/lib/python3.7/smtplib.py", line 855, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 38: ordinal not in range(128)
```

---

Using muttdown 0.3.4, as provided by Debian testing.

**Comment by axgkl** [comment]
same error here, had a look at smtplib and their 'ascii' encoding smells like an old wet dog...
My fix (w/o checks for py2), i.e. only for Py3:

In main.py:

```diff
26c26
<     text = part.get_payload(decode=True)
---
>     text = part.get_payload() 
35c35

189c205,207
<         conn.sendmail(args.envelope_from, args.addresses, rebuilt.as_string())
---
>         conn.sendmail(
>             args.envelope_from, args.addresses, rebuilt.as_string().encode('utf-8')
>         )

```
Wanted to do a PR but after checking the master branch it seems you fixed it as well.
=> a new pip would be nice ;-)

**Comment by jerri** [comment]
Support the request for a new pip. I just spent quite some time to check why this tool didn't work with my umlauts and finally found this issue at the end. The tool is really cool! Would be sad if people don't use it, because the pip-version is too old.
I used pip3 btw.

**Comment by Roguelazer** [comment]
Version 0.3.5 is now released.

**Comment by jerri** [comment]
Awesome! Thanks! :-D
