### ISSUE TITLE
Feature Request: Config option to always compile to text/html (i.e. without !m sigil)?

### ISSUE THREAD

**Issue by rlue** [Roguelazer/muttdown#26]
I've been looking for something like muttdown for years now, and am so pleased to have found it! Thanks so much for you work, really.

I'd like to be able to configure muttdown to compile every single email I write into multipart/alternative without having to prefix messages with !m. Is there any chance you'd be willing to add a config or command line option to that effect? I'd take a stab myself, but I haven't had much of a chance to work with Python yet, and I suspect my contributions wouldn't be exemplary or idiomatic.

**Comment by philpagel** [comment]
I know – this issue is ancient, but I think that would be great because it is a bit confusing for recipients to see the "!m" at the top. (And my OCD has issues with it, too  ;-)  )

**Comment by Roguelazer** [comment]
This is done in v0.4.0

**Comment by philpagel** [comment]
Cool! Thanks a lot!
