### ISSUE TITLE
Doesn't build MIME tree as stated

### ISSUE THREAD

**Issue by oblitum** [Roguelazer/muttdown#4]
From README a tree like this:

```
- multipart/mixed
 |
 -- text/markdown
 |
 -- image/png
```

Should result in a tree like:

```
- multipart/mixed
 |
 -- multipart/alternative
 |
 ---- text/html
 |
 ---- text/markdown
 |
 -- image/png
```

But I couldn't see how that could happen given the current source code, I've then tested it, and as expected the resulting tree is actually:

```
- multipart/alternative
 |
 -- multipart/mixed
 |
 ---- text/markdown
 |
 ---- image/png
 |
 -- multipart/mixed
 |
 ---- text/html
 |
 ---- image/png
```

This is bad because it duplicates attachments.

**Comment by oblitum** [comment]
For reference, I'm now using my own solution that better traverses the MIME tree:

- https://github.com/oblitum/dotfiles/blob/ArchLinux/.local/bin/MIMEmbellish ([blog post about it](http://nosubstance.me/post/mutt-secret-sauce/))

**Comment by Roguelazer** [comment]
Hi @oblitum:

Sorry for the long break; I'm just getting back to this project now. Not sure what I was thinking when I originally wrote this code. #6 should fix this.

**Comment by oblitum** [comment]
Hi @Roguelazer, as I've moved to my solution long ago, you may feel free to close this one if you feel it's solved.
